### ISSUE TITLE
Error when starting container

### ISSUE THREAD

**Issue by haygoodhtpc** [docker-hotio/docker-unpackerr#17]
When I try to start or restart the container (after it working for several days), I get the error that 

`Logger Error: can't open new logfile: open /opt/unpackerr/unpackerr.log: permission denied`

repeatedly. I've checked and the logfile is owned by my docker user and group, and even a chmod to make the file r/w by everyone does not help. I've deleted my entire unpackerr configuration directory except for `unpackerr.conf` and even after totally restarting I have this error. Here's my docker-compose for unpackerr:

`unpackerr:

        container_name: unpackerr

        image: hotio/unpackerr

        restart: always

        network_mode: host

        privileged: true

        volumes:

          - /opt/unpackerr:/opt/unpackerr

          - /opt/unpackerr/unpackerr.conf:/etc/unpackerr/unpackerr.conf

          - /mnt/media:/media

          - /mnt/media/downloads:/downloads

        environment:

          - PUID=1001 %(this is my dockeruser)

          - PGID=998 %(this is the group docker)

          - UMASK=777

          - TZ=America/Chicago

          - DEBUG=yes`

**Comment by hotio** [comment]
That's not a recommended setup as per my Readme....also please use discord for support questions.
